option parsing in hhga script makes it much more ergonomic

diff --git a/scripts/hhga_region b/scripts/hhga_region
--- a/scripts/hhga_region
+++ b/scripts/hhga_region
@@ -1,20 +1,65 @@
 #!/bin/bash
 
-if [ $# -ne 8 ];
+# set an initial value for the flag
+show_help=false
+debug=false
+region=false
+window_size=false
+ref=false
+ground_truth=false
+ground_callable=false
+input_bam=false
+vcf=false
+output_dir=false
+
+if [ $# -eq 0 ];
 then
-echo usage: $0 '[region] [window] [ref] [truth] [targets] [bam] [vcf] [output]'
-echo generates hhga data for this region in the current directory
-exit
+    show_help=true
 fi
 
-region=$1
-window_size=$2
-ref=$3
-ground_truth=$4
-ground_callable=$5
-input_bam=$6
-vcf=$7
-output_dir=$8
+# read the options
+TEMP=`getopt -o r:w:f:t:b:a:v:o:hd --long region:,window:,fasta-ref:,truth:,alignments:,vcf:,output:,help,debug -n 'hhga_region' -- "$@"`
+eval set -- "$TEMP"
+
+# extract options and their arguments into variables.
+while true ; do
+    case "$1" in
+        -r|--region) region=$2 ; shift 2 ;;
+        -w|--window) window_size=$2 ; shift 2 ;;
+        -f|--fasta-ref) ref=$2 ; shift 2 ;;
+        -t|--truth) ground_truth=$2 ; shift 2 ;;
+        -b|--targets) ground_callable=$2 ; shift 2 ;;
+        -a|--alignments) input_bam=$2 ; shift 2 ;;
+        -v|--vcf) vcf=$2 ; shift 2 ;;
+        -o|--output) output_dir=$2 ; shift 2 ;;
+        -h|--help) show_help=true ; shift ;;
+        -d|--debug) debug=true ; shift ;;
+        --) shift ; break ;;
+        *) echo $2 "Internal error!" ; exit 1 ;;
+    esac
+done
+
+if [[    $region == false
+      || $window_size == false
+      || $ref == false
+      || $ground_truth == false
+      || $ground_callable == false
+      || $input_bam == false
+      || $vcf == false
+      || $output_dir == false ]];
+then
+    show_help=true
+fi
+
+if [ $show_help == true ];
+then
+    echo "usage: $0 [options]"
+    echo "options:"
+    echo "    -r [region] -w [window] -f [ref] -t [truth] -b [targets] -a [bam] -v [vcf] -o [output]"
+    echo "    add --debug for debugging output"
+    echo "Generates hhga data for this region in the outut directory."
+    exit
+fi
 
 mkdir -p $output_dir
 
@@ -48,12 +93,6 @@ tabix -h $variant_calls $region \
 vcfintersect -b <(zcat $ground_callable) $normalized_variants | bgziptabix $callable_variants
 vcfintersect -v -b <(zcat $ground_callable) $normalized_variants | bgziptabix $uncallable_variants
 
-#zcat $callable_variants \
-#    | vcfannotategenotypes groundGT - $ground_region \
-#    | vcfunphase - \
-#    | vcfnull2ref - \
-#    | bgziptabix $labeled_variants
-
 zcat $callable_variants \
     | vcfannotategenotypes GT - $ground_region \
     | vcfunphase - \
@@ -63,9 +102,21 @@ zcat $callable_variants \
 hhga -f $ref -r $region -b $input_bam -v $passing_variants -w $window_size -g \
     | gzip >$hhga_genotypes
 
-rm -f $ground_region*
-rm -f $normalized_variants*
-rm -f $callable_variants*
-rm -f $uncallable_variants*
-rm -f $passing_variants*
+if [ $debug == true ];
+then
+   zcat $callable_variants \
+       | vcfannotategenotypes groundGT - $ground_region \
+       | vcfunphase - \
+       | vcfnull2ref - \
+       | bgziptabix $labeled_variants
+fi
+
+if [ $debug == false ];
+then
+    rm -f $ground_region*
+    rm -f $normalized_variants*
+    rm -f $callable_variants*
+    rm -f $uncallable_variants*
+    rm -f $passing_variants*
+fi
 
